export const SEAT_STATUS = {
  AVAILABLE: 'available',
  OCCUPIED: 'occupied',
  SELECTED: 'selected'
};

export const SEAT_CONFIG = {
  TOTAL_SEATS: 40,
  ROWS: 5,
  COLS: 8
};

export const BOOKING_STEPS = {
  SELECTION: 'selection',
  WAITING: 'waiting',
  COMPLETED: 'completed'
};

export const AUTH_ACTIONS = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'LOGOUT',
  SET_LOADING: 'SET_LOADING',
  TOKEN_INVALID: 'TOKEN_INVALID'
};

export const BOOKING_ACTIONS = {
  SELECT_CONCERT: 'SELECT_CONCERT',
  SELECT_SEAT: 'SELECT_SEAT',
  CLEAR_SEAT: 'CLEAR_SEAT',
  START_BOOKING: 'START_BOOKING',
  SET_WAITING_COUNT: 'SET_WAITING_COUNT',
  COMPLETE_BOOKING: 'COMPLETE_BOOKING',
  RESET_BOOKING: 'RESET_BOOKING',
  SET_BOOKING_STEP: 'SET_BOOKING_STEP'
};